import { useEffect, useState } from "react";
import { api } from "../../api.js";
import DangerZone from "../../components/DangerZone.jsx";

const defaults = { email_notifications: true, application_updates: true, sms_alerts: true };

export default function AccountSettings({ user, onBack, onDeleteAccount }) {
  const [preferences, setPreferences] = useState({ ...defaults, ...(user?.notification_preferences || {}) });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => setPreferences({ ...defaults, ...(user?.notification_preferences || {}) }), [user]);
  const toggle = (key) => (value) => setPreferences((current) => ({ ...current, [key]: value }));
  async function savePreferences() { setSaving(true); setError(""); setMessage(""); try { await api.updateNotificationPreferences(preferences); setMessage("Notification preferences saved."); } catch (err) { setError(err?.message || "Unable to save preferences."); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-[var(--theme-cream)] px-6 py-8 text-slate-800"><div className="mx-auto max-w-3xl"><button type="button" onClick={onBack} className="text-sm font-semibold text-[var(--theme-orange)]">← Back to dashboard</button><h1 className="mt-3 text-3xl font-black text-[var(--theme-navy)]">Account settings</h1><p className="mt-1 text-sm text-slate-500">Control notifications, privacy, and account management for {user?.email || "your account"}.</p><section className="mt-8 rounded-2xl border border-[var(--theme-border)] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-[var(--theme-navy)]">Notification Preferences</h2><Toggle label="Email Notifications" description="Receive career and platform updates by email." checked={preferences.email_notifications} onChange={toggle("email_notifications")} /><Toggle label="Application Updates" description="Receive interview and application-status updates." checked={preferences.application_updates} onChange={toggle("application_updates")} /><Toggle label="SMS / WhatsApp Alerts" description="Receive time-sensitive updates by SMS or WhatsApp." checked={preferences.sms_alerts} onChange={toggle("sms_alerts")} />{error && <p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}{message && <p role="status" className="mt-4 text-sm text-emerald-700">{message}</p>}<button type="button" disabled={saving} onClick={savePreferences} className="mt-5 rounded-lg bg-[var(--theme-orange)] px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{saving ? "Saving..." : "Save Preferences"}</button></section><section className="mt-6 rounded-2xl border border-[var(--theme-border)] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-[var(--theme-navy)]">Privacy</h2><p className="mt-2 text-sm text-slate-500">Profile visibility can be managed from your profile.</p></section><section className="mt-6 rounded-2xl border border-[var(--theme-border)] bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-[var(--theme-navy)]">Sign-in and account</h2><p className="mt-2 text-sm text-slate-500">This account uses password-based sign-in and OTP-assisted password recovery.</p><div className="mt-5"><DangerZone role="candidate" onDeleted={onDeleteAccount} /></div></section></div></main>;
}

function Toggle({ label, description, checked, onChange }) { return <label className="flex cursor-pointer items-center justify-between gap-4 border-t border-slate-100 py-4 first:mt-3"><span><span className="block text-sm font-semibold text-slate-800">{label}</span><span className="mt-1 block text-xs text-slate-500">{description}</span></span><input type="checkbox" role="switch" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-5 w-9 cursor-pointer appearance-none rounded-full bg-slate-300 p-0.5 transition checked:bg-[var(--theme-orange)] before:block before:h-4 before:w-4 before:rounded-full before:bg-white before:transition checked:before:translate-x-4" /></label>; }
