import { useEffect, useState } from 'react'
import Tag from '../components/Tag.jsx'
import { api } from '../../../src/api.js'

export default function Jobs() {
  const [jobs, setJobs] = useState([]); const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([api.getAdminJobs({ page: 1, size: 500 }), api.getApplications({ page: 1, size: 100 })]).then(([jobData, applicationData]) => { setJobs(jobData?.items || []); setApplications(applicationData?.items || applicationData || []) }).catch((err) => setError(err.message)).finally(() => setLoading(false)) }, [])
  async function toggle(job) { try { const updated = await api.updateAdminJob(job._id || job.id, { is_published: !job.is_published }); setJobs((current) => current.map((item) => (item._id || item.id) === (job._id || job.id) ? { ...item, ...updated } : item)) } catch (err) { setError(err.message) } }
  async function feature(job) { try { const updated = await api.updateAdminJob(job._id || job.id, { featured: !job.featured }); setJobs((current) => current.map((item) => (item._id || item.id) === (job._id || job.id) ? { ...item, ...updated } : item)) } catch (err) { setError(err.message) } }
  async function remove(job) { if (!window.confirm(`Delete ${job.title || 'this job'}?`)) return; try { await api.deleteAdminJob(job._id || job.id); setJobs((current) => current.filter((item) => (item._id || item.id) !== (job._id || job.id))) } catch (err) { setError(err.message) } }
  function exportCsv() { const rows = [['Job title', 'Company', 'Posted', 'Status'], ...jobs.map((job) => [job.title, job.company_name || 'Company not provided', job.created_at || '', job.is_published ? 'Live' : 'Draft'])]; const csv = rows.map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv' })); link.download = 'mycareerpath-job-posts.csv'; link.click(); URL.revokeObjectURL(link.href) }
  async function moderate(application, status) { try { await api.updateApplicationStatus(application._id || application.id, status); setApplications((current) => current.filter((item) => (item._id || item.id) !== (application._id || application.id))) } catch (err) { setError(err.message) } }
  return <section className="view active"><div className="section-head"><div><h2>Job posts &amp; applications</h2><p>Review listings and candidate applications across the platform</p></div><button className="btn btn-primary" type="button" onClick={exportCsv}>Export CSV</button></div>{error && <p className="auth-error">{error}</p>}<div className="panel"><h3>Live job posts</h3>{loading ? <p>Loading jobs...</p> : <table><thead><tr><th>Job title</th><th>Company</th><th>Applications</th><th>Posted</th><th>Status</th><th>Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job._id || job.id}><td><b>{job.title}</b>{job.featured && <Tag tone="gold">Featured</Tag>}</td><td>{job.company_name || 'Company not provided'}</td><td>{job.applications_count ?? '-'}</td><td>{job.created_at ? new Date(job.created_at).toLocaleDateString() : '-'}</td><td><Tag tone={job.is_published ? 'teal' : 'flat'}>{job.is_published ? 'Live' : job.flagged ? 'Flagged' : 'Draft'}</Tag></td><td className="row-actions"><button className="btn btn-ghost" onClick={() => toggle(job)}>{job.is_published ? 'Close' : 'Publish'}</button><button className="btn btn-ghost" onClick={() => feature(job)}>{job.featured ? 'Unfeature' : 'Feature'}</button><button className="btn btn-ghost" onClick={() => remove(job)}>Remove</button></td></tr>)}</tbody></table>}{!loading && jobs.length === 0 && <p>No job posts found.</p>}</div><div className="panel moderation-panel"><h3>Applications awaiting moderation</h3><div className="sub">Quickly approve or reject new applications</div>{applications.filter((application) => !['hired', 'rejected'].includes(application.status)).length === 0 ? <p>No applications awaiting moderation.</p> : <table><thead><tr><th>Candidate</th><th>Job</th><th>Submitted</th><th>Status</th><th>Review</th></tr></thead><tbody>{applications.filter((application) => !['hired', 'rejected'].includes(application.status)).map((application) => <tr key={application._id || application.id}><td>{application.candidate_name || application.candidate_email || '-'}</td><td>{application.job_title || '-'}</td><td>{application.created_at ? new Date(application.created_at).toLocaleDateString() : '-'}</td><td><Tag tone="gold">{application.status || 'In review'}</Tag></td><td className="row-actions"><button className="icon-btn" title="Approve" onClick={() => moderate(application, 'screening')}>✓</button><button className="icon-btn" title="Reject" onClick={() => moderate(application, 'rejected')}>✕</button></td></tr>)}</tbody></table>}</div></section>
}
