import { useEffect, useState } from 'react'
import BarChart from '../components/BarChart.jsx'
import { api } from '../../../src/api.js'
import { reports as reportCards } from '../data.js'

export default function Reports() {
  const [metrics, setMetrics] = useState(null); const [error, setError] = useState(''); const [registrations, setRegistrations] = useState([]); const [chart, setChart] = useState([]); const [downloading, setDownloading] = useState('')
  const toChart = (series) => { const max = Math.max(...series.map((item) => item.count), 1); return series.map((item) => ({ month: item.month.slice(5), height: item.count ? Math.max(Math.round((item.count / max) * 100), 5) : 0 })) }
  useEffect(() => { api.getAdminReports().then((data) => { setMetrics(data); setRegistrations(toChart(data?.registrations || [])); setChart(toChart(data?.applications || [])) }).catch((err) => setError(err.message)) }, [])
  async function downloadReport(kind) { setError(''); setDownloading(kind); try { const blob = await api.downloadAdminReport(kind); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `mycareerpath-${kind}-report.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url) } catch (err) { setError(err.message || 'Unable to generate report.') } finally { setDownloading('') } }
  return <section className="view active"><div className="section-head"><div><h2>Reports</h2><p>Job reports, candidate outcomes, and platform performance</p></div></div>{error && <p className="auth-error">{error}</p>}<div className="report-card-grid">{reportCards.map((report) => { const kind = report.title === 'Job reports' ? 'jobs' : report.title === 'Candidate reports' ? 'candidates' : ''; return <article className="report-card" key={report.title}><div><h3>{report.title}</h3><p>{report.desc}</p></div><div className="report-card-meta"><span>{report.metaLabel1}<b>{report.metaValue1}</b></span><span>{report.metaLabel2}<b>{report.metaValue2}</b></span></div><button className={`btn ${report.primary ? 'btn-primary' : 'btn-ghost'}`} type="button" disabled={Boolean(kind && downloading)} onClick={() => kind ? downloadReport(kind) : window.alert(`${report.title} is available in the platform insights.`)}>{kind && downloading === kind ? 'Generating…' : report.cta}</button></article>})}</div>{metrics && <div className="grid-2"><div className="panel"><h3>Monthly registration growth</h3><div className="sub">Last twelve months</div>{registrations.length ? <BarChart data={registrations} /> : <p>No registration data yet.</p>}</div><div className="panel"><h3>Application volume</h3><div className="sub">Last twelve months</div>{chart.length ? <BarChart data={chart} /> : <p>No application data yet.</p>}</div></div>}</section>
}
