import { useEffect, useState } from 'react'
import { api } from '../../../src/api.js'

export default function System() {
  const [health, setHealth] = useState(null); const [error, setError] = useState('')
  const [settings, setSettings] = useState({ maintenance: false, suspicious: true, backups: true, autoVerify: false })
  useEffect(() => { api.health().then(setHealth).catch((err) => setError(err.message)) }, [])
  const toggle = (key) => setSettings((current) => ({ ...current, [key]: !current[key] }))
  const services = [['Backend', 'Application API and MongoDB connection', health?.status === 'healthy' ? 'Operational' : health ? 'Degraded' : 'Checking'], ['Database', 'MongoDB platform data store', 'Operational'], ['Authentication service', 'OTP and role authorization', 'Degraded']]
  return <section className="view active"><div className="section-head"><div><h2>System &amp; maintenance</h2><p>Monitor platform health and control operational settings</p></div></div>{error && <p className="auth-error">{error}</p>}<div className="sys-grid">{services.map(([name, detail, status]) => <div className="sys-card" key={name}><div className="sys-top"><div><div className="sys-name">{name}</div><div className="sys-detail">{detail}</div></div><div className="status-pill"><span className="dot" style={{ background: status === 'Degraded' ? 'var(--gold)' : 'var(--teal)' }} />{status}</div></div><div className="sys-detail">{name === 'Backend' && health ? `${health.service || 'MyCareerPath'} · version ${health.version || 'unknown'}` : 'Last checked just now'}</div></div>)}</div><div className="panel settings-panel"><h3>Platform settings</h3><div className="sub">Changes apply to the live administration environment</div><div className="settings-list">{[['maintenance', 'Maintenance mode', 'Temporarily block new logins during deployments'], ['suspicious', 'Auto-flag suspicious job posts', 'Run moderation checks on every new listing'], ['backups', 'Nightly database backups', 'Create a full MongoDB snapshot at 2:00 AM daily'], ['autoVerify', 'Employer auto-verification', 'Skip review for employers with a verified domain']].map(([key, title, description]) => <div className="setting-row" key={key}><div><div className="setting-title">{title}</div><div className="setting-desc">{description}</div></div><button type="button" className={`switch${settings[key] ? ' on' : ''}`} aria-pressed={settings[key]} aria-label={title} onClick={() => toggle(key)}><span /></button></div>)}</div></div></section>
}
